# Generated by Django 3.2.6 on 2021-08-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
